### PR TITLE
Fixing template updates for onsite_notification - Bugfix/715

### PR DESCRIPTION
**Pull request by EvanParish**
Just a small change to make sure the "onsite_notification" value can be updated on templates.

### CODE REVIEW

**Comment by EvanParish** [comment]
Hey, @Jake-Uhteg this should be an easy one for QA!

**Review by jessecanderson — APPROVED** [review]
Looks good to me.

**Comment by mjones-oddball** [comment]
@EvanParish I just huddled with @k-macmillan on this and QA. Since @Jake-Uhteg doesn't have AWS access yet can you pair with him and walk through the testing on Dev together so he can learn, write test cases, and plan for future testing? As long as it looks good to you both once ready onsite updates can get pushed to Staging. Let me know if you have any questions/concerns. Goal is to wrap up our work and validation by end of day Friday so DMC can trigger a debt on staging next week and we'll see if the onsite notification shows up in va.gov.

**Review by k-macmillan — APPROVED** [review]

**Comment by EvanParish** [comment]
Pictures to show template update sticks.
Before Update:
get_template_response_before_update

After Update:
get_template_response_after_update

**Comment by EvanParish** [comment]
@mjones-oddball Sounds good! I'm planning on getting together with Jake once we can get the onsite code changes and template update fix together in Dev. Then I can walk him through the whole process of Onsite Notifications.

**Pull request merged**
