### PR TITLE
#1215 Add unit tests, and improve API documentation, for creating and updating ServiceSmsSender instances

### PR DESCRIPTION
**Pull request by kalbfled**
# Description

The bug outlined in the ticket was inadvertently fixed at some point.  These changes:
1. Add unit tests to codify the intended (and actual) behavior
2. Add sms_sender_specifics to the schema for the POST route to add a new ServiceSmsSender instance.  This attribute was only part of the update route, which seems like an oversight.
3. Require a valid update request to include at least one attribute to update
4. Update the OpenAPI and Postman docs.  For Postman, this includes setting the default request value of "is_default" to False, rather than True.  For OpenAPI, this includes proper specification of request bodies and refactoring to declare some URL parameters at the "path" level rather than for each verb (GET or POST) of that path.

issue #1215

## Useful documentation

- [Swagger Editor](https://editor-next.swagger.io/) - Load [this](https://raw.githubusercontent.com/department-of-veterans-affairs/notification-api/1215-sms-sender/documents/openapi/openapi.yaml) URL to preview the OpenAPI changes
- [OpenAPI 3.0.0 spec](https://spec.openapis.org/oas/v3.0.0)
- [JSON schema reference](https://json-schema.org/understanding-json-schema/reference)

## Type of change

Please check the relevant option(s).

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update
- [ ] Documentation changes only

## How Has This Been Tested?

- [x] Unit tests pass
- [x] [Deployed](https://github.com/department-of-veterans-affairs/notification-api/actions/runs/8742506068)
- [x] Cris and I manually verified the intended behavior using Postman

## Checklist

- [x] I have assigned myself to this PR
- [x] PR has an appropriate title: #9999 - What the thing does
- [x] PR has a detailed description, including links to specific documentation
- [x] I have added the [appropriate labels](https://github.com/department-of-veterans-affairs/notification-api/blob/master/.github/release.yaml) to the PR.
- [x] I did not remove any parts of the template, such as checkboxes even if they are not used
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to any documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have ensured the latest master is merged into my branch and all checks are green prior to review
- [x] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules
- [x] The ticket is now moved into the DEV test column

### CODE REVIEW

**Review by cris-oddball — CHANGES_REQUESTED** [review]
Still looking at this, but in the openapi.yaml file, please update the version from 1.0.6 to 1.0.7.

**Review by cris-oddball — CHANGES_REQUESTED** [review]
Not really sure what part of the `openapi.yaml `addresses this, but more changes:

The example value for the POST payload and the example 201 response have `"is_default": true,` - since the default value in Postman is false, should these all be false?

The example value for the POST payload is `"sms_sender_specifics": {}`. As near as I can tell, this should have an attribute (are these more?)

```
        "sms_sender_specifics": {
            "messaging_service_sid": "MG0000000000000000000000"
        },
```

Note that I did not use a real SID here. Maybe something in the description as to what this value represents (right now, it's the Twilio messaging service SID).

**Review by MackHalliday — COMMENTED** [review]
LGTM 🚀

**Review by MackHalliday — DISMISSED** [review]

**Review by MackHalliday — DISMISSED** [review]
Reapproved

**Review by cris-oddball — APPROVED** [review]

**Review by MackHalliday — APPROVED** [review]

**Pull request merged**
